### ISSUE TITLE
Instead of Name of user, but there's an id from that.

### ISSUE THREAD

**Issue by reopucino** [gimid/warga#11]
![Screenshot from 2023-09-22 12-41-43_edit](https://github.com/gimid/warga/assets/3539016/16225181-b387-4825-8c4f-f52d19251a38)

I thought that should be a name, instead of an ID from the post

**Comment by igrir** [comment]
ooooh, iya, itu ID dari postnya. sebenernya pengen bikinnya jadi berthread kayak di forem, tapi nggak sempat, ya sudahlah jadinya bikin quick patch dulu 😂 

sebenernya ini cara ngobrol ala 4chan. balasannya ditandain pakai id postingan
![image](https://github.com/gimid/warga/assets/613950/53e6998f-1085-4570-be0f-7699b6720e3b)

**Comment by reopucino** [comment]
oh.. ngerti2.. berarti tinggal patchnya aja yah.. ya wes.. paling ngga ada di list aja dulu :)

**Comment by igrir** [comment]
Fitur threaded udah rilis! https://github.com/gimid/warga/discussions/17

Harusnya aman dan bisa diintip di commitan 87be6472d5287210bbd80cf983db5334f9380e9b
